export const productList = [
  {
    productid: "1",
    url: "https://www.funble.kr/img/building_img2.jpg",
    name: "롯데 시그니엘 1호",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "2",
    url: "https://원당역롯데캐슬스카이엘.com/resource/img/main/vis_05.jpg",
    name: "해운데 엘시티",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "3",
    url: "https://cdn.dtoday.co.kr/news/photo/201601/197625_118565_755.jpg",
    name: "반포 자이아파트",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "4",
    url: "https://www.funble.kr/img/building_img2.jpg",
    name: "롯데 시그니엘 1호",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "5",
    url: "https://원당역롯데캐슬스카이엘.com/resource/img/main/vis_05.jpg",
    name: "해운데 엘시티",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "6",
    url: "https://cdn.dtoday.co.kr/news/photo/201601/197625_118565_755.jpg",
    name: "반포 자이아파트",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "7",
    url: "https://www.funble.kr/img/building_img2.jpg",
    name: "롯데 시그니엘 1호",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "8",
    url: "https://원당역롯데캐슬스카이엘.com/resource/img/main/vis_05.jpg",
    name: "해운데 엘시티",
    price: "300000",
    type: "부동산",
  },
  {
    productid: "9",
    url: "https://cdn.dtoday.co.kr/news/photo/201601/197625_118565_755.jpg",
    name: "반포 자이아파트",
    price: "300000",
    type: "부동산",
  },
];
